import React from "react";
import { useNavigate } from "react-router-dom";
import { motion } from "framer-motion";
import { FiMap, FiChevronRight, FiCheckCircle, FiHome, FiLayout } from "react-icons/fi";
import "./CareerRoadmap.css";

export default function CareerRoadmap() {
  const navigate = useNavigate();

  const roadmapItems = [
    { title: "Foundational Pillar", desc: "Advanced Java & Spring Boot mastery.", status: "Primary Focus" },
    { title: "Architecture Peak", desc: "Microservices & Distributed Systems.", status: "Month 3-5" },
    { title: "Professional Debut", desc: "Career Mentorship & FAANG Mock Interviews.", status: "Graduation" }
  ];

  return (
    <div className="roadmap-container">
      <div className="roadmap-v4-wrap">
        <header className="roadmap-header-v4">
          <FiMap className="map-icon-v4" />
          <span className="roadmap-tag-v4">Your Personal Roadmap</span>
          <h1>Success Strategy</h1>
          <p>Generated by our experts for your career acceleration.</p>
        </header>

        <div className="roadmap-track-v4">
          {roadmapItems.map((item, i) => (
            <motion.div 
              key={i} 
              className="roadmap-step-v4"
              initial={{ opacity: 0, x: -20 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ delay: i * 0.2 }}
            >
              <div className="step-num-v4">{i + 1}</div>
              <div className="step-content-v4">
                <div className="c-header">
                  <h3>{item.title}</h3>
                  <span className="c-status">{item.status}</span>
                </div>
                <p>{item.desc}</p>
              </div>
              <FiChevronRight className="chevron-v4" />
            </motion.div>
          ))}
        </div>

        <div className="roadmap-cta-v4">
          <div className="enroll-card-v4">
            <FiCheckCircle className="check-v4" />
            <h3>Start Your Journey</h3>
            <p>Enroll in the recommended track today and get 20% off.</p>
            <button className="btn-enroll-v4" onClick={() => navigate("/courses")}>
              Unlock Full Access
            </button>
          </div>
        </div>

        <button className="btn-home-v4" onClick={() => navigate("/")}>
          <FiHome /> Back to Landing Page
        </button>
      </div>

      {/* Back Button */}
      <button className="global-back-btn-v4" onClick={() => navigate(-1)}>
        <FiArrowRight style={{ transform: "rotate(180deg)" }} /> Back
      </button>
    </div>
  );
}
